### ISSUE TITLE
lucetc no longer looks at wasm name sections

### ISSUE THREAD

**Issue by pchickey** [bytecodealliance/lucet#152]
Before the refactor to use `cranelift-wasm` (#44), lucetc would use the name section in a WebAssembly module to give more useful object file symbol names to non-exported functions.

Currently, lucetc uses `cranelift-wasm`'s `ModuleEnvironment` trait to parse sections out of a WebAssembly module, but `ModuleEnvironment` does not expose any name sections it comes across. We could either patch `ModuleEnvironment` to support name sections, or we could stop using `ModuleEnvironment`/`cranelift_wasm::translate_module`, and just create a `ModuleInfo` by using `wasmparser` directly.

**Comment by data-pup** [comment]
I would love to try and take a swing at this!  yurydelendik/wasmparser.rs#70 added a `NameSectionReader` to the wasmparser crate, so do you think that patching `ModuleEnvironment` would be worth trying first?

If you have advice on how to get this done, any help is appreciated! Otherwise, I can follow up with questions as they come up.

**Comment by pchickey** [comment]
Cool, this would be a great one to do next!

You could patch `ModuleEnvironment` first if you want. However, having talked it through with @sunfishcode and others, I don't think there's a really compelling reason for the `ModuleEnvironment` trait to stick around at all - consumers should just inline `cranelift_wasm::translate_module`.

That would be a little bit of a bigger change, but I think it would leave us in a better place. We want to support more extensions to Wasm MVP soon and it will just create work to patch `ModuleEnvironment` to support each as we go, rather than just get them from `wasmparser`.

**Comment by data-pup** [comment]
I'm just about done w/ CraneStation/cranelift#811, which will let us get name information out of the module. Once that's landed, I'll be able to continue work on this on the lucet side of things. :slightly_smiling_face:
