### ISSUE TITLE
Benchmarks: add use of binaryen wasm-opt 

### ISSUE THREAD

**Issue by pchickey** [bytecodealliance/lucet#208]
Derek Schuff encouraged me to use binaryen's wasm-opt optimizer on the wasm emitted by llvm - this is one additional pass that Emscripten performs, and it apparently makes a big difference in performance.

**Comment by jedisct1** [comment]
The current stable version of `wasm-opt` segfaults with our benchmarking suite.

I'm currently trying to see if this is a recent regression, and what exact optimization pass is doing this.
