### ISSUE TITLE
Allow use of 4GB aligned heaps to optimize performance of pointer swizzling

### ISSUE THREAD

**Issue by shravanrn** [bytecodealliance/lucet#276]
**Context**
This is part of a series of bugs that I spoke to @tyler @pchickey about. We are currently using  Lucet to sandbox libraries in C++ applications. The idea behind this is that using a wasm sandboxed version of the library allows ensuring that a memory safety issue in the library does not automatically result in a memory safety vulnerability in the full application. One of the  consumers of this work is the Firefox web browser. 

**Problem**
Since our use case involves sandboxing libraries and not entire applications, data structures may be shared between application and the wasm sandboxed library. Such data structures may contain pointer fields. Given that the representation of pointers differ between the application (which uses simple 64-bit addresses) and the wasm sandboxed library (which uses 32-bit offsets from the sandbox memory base), we need to convert/swizzle pointers at the appropriate locations. 

One particularly efficient and elegant approach to swizzle pointers automatically using only C++ operator overloading (if you are curious, this is implemented [here](https://github.com/PLSysSec/rlbox_lucet_sandbox/blob/master/include/rlbox_lucet_sandbox.hpp#L533)) requires the heap to be aligned according to its size. For instance, a 4GB heap would need to be 4GB aligned, a 1GB heap would need to 1GB aligned etc.

**Actions**
@pchickey mentioned that I could submit a patch for this alignment. I already have a prototype for the same and can clean it up and submit this shortly. The plan is to implement this under an alternate constructor of MmapRegion.

Please let me know if you have any thoughts/concerns.

**Comment by acfoltzer** [comment]
This sounds great! I'm guessing this is mainly a change to the `mmap` call in `MmapRegion::create_slot()`?

**Comment by shravanrn** [comment]
Yup! I have a slightly hacky prototype [here](https://github.com/PLSysSec/lucet_sandbox_compiler/commit/a1caf3d812f5bbd974b4219e71f7da8bd7eab2c7#diff-612f63d1d0d40b2d830f75b1c53a3958R232), which I am in the process of cleaning up and submitting a PR for

**Comment by shravanrn** [comment]
Hi, sorry for the delay here. I have rebased and added some tests. Does this look ok?
