### ISSUE TITLE
Benchmark `lucetc`

### ISSUE THREAD

**Issue by pchickey** [bytecodealliance/lucet#310]
Our sightglass benchmarks measure the code emitted by `lucetc` against native. However, we have no benchmarks of `lucetc`'s runtime performance!

We should measure lucetc's run time and memory footprint at each of the available optimization levels.

**Comment by acfoltzer** [comment]
We actually do have the start of a suite here: https://github.com/fastly/lucet/blob/master/benchmarks/lucet-benchmarks/src/compile.rs

Definitely needs to be built out, though. We need some good sample programs to use.
