### ISSUE TITLE
Switch from failure to thiserror

### ISSUE THREAD

**Issue by jedisct1** [bytecodealliance/lucet#357]
For error handling, we currently use the `failure` crate everywhere.

`failure` was great when it was released and the standard `Error` trait didn't support backtraces yet. But things have changed since.

Backtraces are now supported in `std::error::Error`, so we should use it instead of a custom trait.

Cranelift [switched](https://github.com/CraneStation/cranelift/pull/1188) to `thiserror`, that is lightweight and does everything we need, so we may want to do the same.

**Comment by acfoltzer** [comment]
I'm in favor of this, plus using the complementary `anyhow` to collect errors in our more informal binary targets (places we would use `failure::Error` currently). As fun as this would be to take on myself, I marked this as a good introductory issue.
