### ISSUE TITLE
Preemption?

### ISSUE THREAD

**Issue by dpc** [bytecodealliance/lucet#365]
Please excuse me if I missed it, but I'm trying to figure out how do deal with preempting long running wasm program. If I'm running a 3rd party wasm binary, the simplest attack is for the binary to just never yield/terminate and keep using cpu. How am I supposed to handle that with `lucent-runtime`? Should I just create a new process, so I can just forcefully kill it with a signal if it is running too long?

**Comment by pchickey** [comment]
Hi @dpc, great question. @iximeow recently completed (in #150) the implementation of a mechanism to terminate a lucet-runtime instance from another thread in the same process. The `Instance::kill_switch` method (here)[https://github.com/bytecodealliance/lucet/blob/master/lucet-runtime/lucet-runtime-internals/src/instance.rs#L696] gives a struct you can use to terminate an instance, and the (tests)[https://github.com/bytecodealliance/lucet/blob/master/lucet-runtime/lucet-runtime-tests/src/timeout.rs] show a couple of different ways this mechanism can be used.

**Comment by dpc** [comment]
Great timing! Thank you!
