### ISSUE TITLE
HOST_BASE_PREFIX does not evaluate correctly when running source devenv_setenv.sh

### ISSUE THREAD

**Issue by jimternet** [bytecodealliance/lucet#372]
https://github.com/bytecodealliance/lucet/blob/f312d0859817fbcc08b5913b300c0c49e0ecf0f5/config.inc#L4

**Comment by jedisct1** [comment]
Hi,

Can you clarify what the issue is?

What did you do, what did you expect, what happened and how to reproduce this?

**Comment by jimternet** [comment]
sorry when I was running `source ./devenv_setenv.sh` it was erroring on that line - 
I think it was adding a `.` between `HOST_BASE_PREFIX` and the `"/helpers/install.sh"`

**Comment by jedisct1** [comment]
Can you try `source devenv_setenv.sh`?

Or if Lucet has been installed (with `make install`), use the full path.
