### ISSUE TITLE
"Too many open files" when creating multiple Lucet "vms"

### ISSUE THREAD

**Issue by gektorbr** [bytecodealliance/lucet#389]
Lucet runtime crashes when starting multiple instances. In my experiment I create many threads (1000 +) and each one does `lucet_dl_module_load, ..., lucet_instance_run`. The guest callback freezes the thread imitating a running function. The problem is that for each instance the runtime opens 3 files and they never become closed (assuming I'm not missing something). This causes the runtime to crash.

**Comment by pchickey** [comment]
For a Lucet instance that uses `wasi`, we open 3 fifos to implement `stdin`, `stdout`, and `stderr`. These files are closed when the instance is dropped.

@iximeow is working on changes to `wasi-common` that will allow us to implement the stdio streams without creating an OS file. We expect this to land within the next few weeks.

**Comment by gektorbr** [comment]
Thanks!
