### ISSUE TITLE
question for lucetc-wasi 

### ISSUE THREAD

**Issue by zs33** [bytecodealliance/lucet#394]
Hi, i only found how to use lucetc-wasi in wiki, but i can't find its working principle, is there any article describing it?  Thank you very much.

**Comment by fst-crenshaw** [comment]
Thanks for your question!  I'm not 100% certain what you mean by "working principle."  I wonder whether this article might help you:

https://www.fastly.com/blog/announcing-lucet-fastly-native-webassembly-compiler-runtime
