### ISSUE TITLE
Generating a standalone native executable

### ISSUE THREAD

**Issue by danaugrs** [bytecodealliance/lucet#396]
Hi, and thanks for this awesome project!

How would I go about creating a WASI-enabled standalone native executable from a WASM module such as the one below?

It doesn't need to be sandboxed. Should I package it with the `lucet-wasi` runtime, or maybe with [`wasm-micro-runtime`](https://github.com/bytecodealliance/wasm-micro-runtime)? How would I do that?

I'm thinking ideally I would be able to generate a ".o" object file containing the Lucet WASI runtime implementations and link it with my own object file that was generated by `lucetc`. How could I generate such an object file containing Lucet's WASI runtime implementations?

Thanks in advance!

```wasm
(module
    (import "wasi_unstable" "fd_write" (func $fd_write (param i32 i32 i32 i32) (result i32)))
    (memory 1)
    (export "memory" (memory 0))
    (data (i32.const 8) "hello world\n")
    (func $main (export "_start")
        (i32.store (i32.const 0) (i32.const 8))
        (i32.store (i32.const 4) (i32.const 12))
        (call $fd_write
            (i32.const 1)  ;; file_descriptor - 1 for stdout
            (i32.const 0)  ;; *iovs - The pointer to the iov array, which is stored at memory location 0
            (i32.const 1)  ;; iovs_len - We're printing 1 string stored in an iov - so one.
            (i32.const 20) ;; nwritten - A place in memory to store the number of bytes written
        )
        drop ;; Discard the number of bytes written from the top of the stack
    )
)
```

**Comment by jedisct1** [comment]
The Lucet runtime requires an external shared library. It shouldn't take much to directly use statically liked symbols, but the current API doesn't allow this.

However, this is trivial to do with [Wasmtime](https://wasmtime.dev/), where a module can be instantiated from a binary-encoded WebAssembly module: https://docs.rs/wasmtime/0.9.0/wasmtime/struct.Module.html

**Comment by danaugrs** [comment]
Great - that looks like the best option! Thanks!
