### ISSUE TITLE
Argument struct for `lucetc::Compiler::new()`

### ISSUE THREAD

**Issue by acfoltzer** [bytecodealliance/lucet#414]
Inspired by https://github.com/bytecodealliance/lucet/pull/405

The number of arguments here is getting out of hand, and it's easy to forget all the places that must be updated when adding a new one. For example, the new functionality in #405 is only available via the API, not the command line. Cleaning this up, and perhaps even sharing a data structure with the command-line parser would improve this a lot.

**Comment by pchickey** [comment]
Closed #418
