### ISSUE TITLE
lucet-validate should accept multiple witx files

### ISSUE THREAD

**Issue by acfoltzer** [bytecodealliance/lucet#434]
Currently `lucet-validate` only accepts a single witx spec:

```
lucet-validate [FLAGS] <module> <witx>
```

We would like to be able to validate a module that imports functions from multiple witx specs, though, since WASI is likely to be fissioned into multiple modules, and we might want to have WASI plus an embedder-specific interface.

A module should be valid if and only if its import functions are all contained in the set of witx specs, and if it exports **all** of the exports defined in the specs.

To prevent the command-line args from getting _too_ confusing we should probably make the witx arguments a flag rather than a bare argument, so they can be repeated or reordered.

```
lucet-validate --witx wasi.witx --witx q3dm17.witx <module>
```

**Comment by samrat** [comment]
I was planning on taking a stab at this but looks like this has already been fixed with https://github.com/bytecodealliance/lucet/commit/667976ca73ef9bde6bbbcc4a5b099e9157d3ebb0

**Comment by pchickey** [comment]
Ah, thanks, forgot to close this. It looks like we haven't done a great job coming up with good first issues lately, we'll see if we can file some more today.
