### ISSUE TITLE
builds are broken due to wasmtime pch/wiggle_relative_paths branch being deleted

### ISSUE THREAD

**Issue by froydnj** [bytecodealliance/lucet#449]
e.g. we have:

https://github.com/bytecodealliance/lucet/blob/62f41282f3bc65c42217b7f75f7cfb2b390231db/lucet-wiggle/Cargo.toml#L17-L24

But bytecodealliance/wasmtime#1294 indicates that branch got deleted.

/cc @pchickey

**Comment by pchickey** [comment]
Ah shit, sorry, I will fix that promptly

**Comment by pchickey** [comment]
Pushed directly to master 61babda

**Comment by froydnj** [comment]
Thank you!
