### ISSUE TITLE
Instances are not wholly cleaned up when they error out due to unexpected signal stack sizes.

### ISSUE THREAD

**Issue by fst-crenshaw** [bytecodealliance/lucet#455]
The moment when the lucet runtime switches into a guest to extract the instance's result is a function called `swap_and_return`.   If the call to `self.with_signals_on` returns with an Error resulting from an unexpected signal stack size, `swap_and_return` returns without cleaning up the borrowed instance.  As in, this doesn't happen.

```
        CURRENT_INSTANCE.with(|current_instance| {
            *current_instance.borrow_mut() = None;
        });

```

That moment is here:
https://github.com/bytecodealliance/lucet/blob/c765316fe108c10b6815236ede70b841b8ec3b57/lucet-runtime/lucet-runtime-internals/src/instance.rs#L972

To reproduce the issue:

1. Go to `~/lucet-runtime/lucet-runtime-internal`
2. Run `cargo test -- --test-threads=1`

The result:

```
---- alloc::tests::reject_sigstack_smaller_than_min stdout ----
thread 'main' panicked at 'no other instance is running on this thread', lucet-runtime/lucet-runtime-internals/src/instance.rs:956:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
failures:
  alloc::tests::reject_sigstack_smaller_than_min
test result: FAILED. 65 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
error: test failed, to rerun pass '--lib'
```

Tactically, what happens: 

This test fails (expectedly) but the cleanup doesn't happen.
alloc::tests::reject_debug_sigstack_smaller_than_12kib

So this test fails (unexpectedly):
alloc::tests::reject_sigstack_smaller_than_min

**Comment by acfoltzer** [comment]
https://github.com/bytecodealliance/lucet/commit/058cc8562e58d4e1bd6ac041e0567f7c698c1c89
