### ISSUE TITLE
Change default branch name

### ISSUE THREAD

**Issue by tyler** [bytecodealliance/lucet#550]
As a policy, the Bytecode Alliance is changing the default branch names in all repositories. We would like for all projects to change the default to `main` by June 26. (We mention June 26th because there is some suggestion that GitHub may be adding the ability to make this process more seamless. Feel free to wait for that, but only up to June 26.)

Please consider this a tracking issue. It is not intended for public debate.

- [x] Change branch name
- [x] Update CI
- [x] Update build scripts
- [x] Update documentation

**Comment by pchickey** [comment]
#555 changes all references in the repo itself
