### ISSUE TITLE
Errors while executing hello world example with lucetc-wasi

### ISSUE THREAD

**Issue by sergiizubchevskyy** [bytecodealliance/lucet#573]
Hello!

I've installed Lucet by following documentation here: https://bytecodealliance.github.io/lucet/Compiling-on-Linux.html, and opted for the first installation method.

After that I compiled hello world example using steps described here: https://bytecodealliance.github.io/lucet/Your-first-Lucet-application.html

After compiling hello.wasm file I execute it with Wasmtime (v 0.19.0) and it prints "Hello World" as expected.

However after generating hello.so file and attempting to execute it with lucetc-wasi command I'm getting errors like: unexpected char, unexpected EOF, unexpected token etc.

Example:
1: 
![image](https://user-images.githubusercontent.com/44066210/88914731-f3f48780-d25a-11ea-8fb0-80b306fc824d.png)

2:
![image](https://user-images.githubusercontent.com/44066210/88914775-07075780-d25b-11ea-8533-8e7b858ec991.png)

3:
![image](https://user-images.githubusercontent.com/44066210/88914796-14244680-d25b-11ea-8e1e-09f74bfc7d50.png)

Also, I might be going the wrong path here but I'm attempting to use Lucet to produce some sort of AOT file that will skip the compilation performed by Wasmtime. I assumed that Wasmtime should be able to consume hello.so, however this is not the case, it outputs the following: 
![image](https://user-images.githubusercontent.com/44066210/88914938-53eb2e00-d25b-11ea-9845-0b213133cb20.png)

Could you point me in the right directions here? Am I understanding correctly the Lucet's usage?

Thank you in advance.

**Comment by jedisct1** [comment]
Hi!

lucetc-wasi is the compiler. It cannot run code. 

The resulting .so (or .dylib) file must be run with lucet-wasi, which is a different tool.

**Comment by sz-ctw** [comment]
Wow! Thank you for such a fast answer! I'm reinstalling the Lucet so will try as soon as it is installed.

And what about the Wasmtime? Is there a way to pass compiled .so object or similar to avoid compilation by JIT compiler of Wasmtime?

**Comment by sz-ctw** [comment]
You're correct, invoking the lucet-wasi tool solves the issue with warning. From what I read in the meantime, I've got an impression that there is no way (at least for now) to use some sort of AOT with the Wasmtime, and I had am impression that Wasmtime is the runtime used by Lucet but after searching I think Wasmtime is used to provide some files for build support.

**Comment by jedisct1** [comment]
Wasmtime includes a cache: https://bytecodealliance.github.io/wasmtime/cli-cache.html - Once code has been cached, it doesn’t need to be recompiled any more.

**Comment by sergiizubchevskyy** [comment]
Thank you! 

I've done some tests and according to Valgrind Massif and got a bit surprised since consecutive executions with cache enabled still got almost 4MiB, when comparing with Wasmtime JIT (cache disabled) 4.4MiB... It is improvement, but not as much as I was expecting.

Check this out:
1st cache enabled execution:
![image](https://user-images.githubusercontent.com/44066210/88946733-83179480-d287-11ea-9406-ab7db1e0004e.png)

2nd cache enabled execution:
![image](https://user-images.githubusercontent.com/44066210/88946785-9296dd80-d287-11ea-97ae-f92bc8040b57.png)

3rd cache enabled execution:
![image](https://user-images.githubusercontent.com/44066210/88946835-a4788080-d287-11ea-9545-e93bb7637d88.png)

And now Wasmtime, cache disabled:
![image](https://user-images.githubusercontent.com/44066210/88946892-b4906000-d287-11ea-968c-9b17fcb920f1.png)

But this is way beyond Lucet's responsibility! 

Thank you again jedisct1! You really helped me a lot.

I think this issue can be closed, you prefer me to close it?
