### ISSUE TITLE
Screencast in README is too fast to read

### ISSUE THREAD

**Issue by ctsrc** [bytecodealliance/lucet#613]
Hi, the screencast linked to from the README has some text pasted into it which unfortunately is on screen for too short amount of time to read. Would really appreciate if a new screencast is produced that gives time to read what is being said.

**Comment by jedisct1** [comment]
The screencast was just intended to be eye-catching.

What happens during this screencast is exactly what is documented here: https://bytecodealliance.github.io/lucet/Your-first-Lucet-application.html

**Comment by ctsrc** [comment]
Ok thank you 🙏🏻
